### ISSUE TITLE
Tytuł strony internetowej

### ISSUE THREAD

**Issue by arbuz93** [arbuz-team/rosettabakalie#1]
Tytuł strony internetowej w przeglądarce Firefox trochę się rozjechał i wygląda tak:
![Alt Text](https://dl.dropboxusercontent.com/u/8297754/screenshots/Przechwycenie%20obrazu%20ekranu_2016-05-20_23-52-09.png)
@Drego31

**Comment by Drego31** [comment]
Rozumiem, już to naprawiam
