### ISSUE TITLE
Błąd z wyświetlaniem menu zakładek

### ISSUE THREAD

**Issue by Drego31** [arbuz-team/rosettabakalie#2]
Menu zakładek nie wyświetla się w pliku `szablon_produktu.html` @arbuz93 

![Alt tekst](https://dl.dropboxusercontent.com/u/48352926/screenshots/Screenshot_20160523_001117.png)

**Comment by arbuz93** [comment]
Zajmę się tym, jak tylko wrócę do domu.

**Comment by arbuz93** [comment]
Zamykam.
